'use strict';
const form=document.getElementById('calculator-form');
const kind=document.getElementById('kind'), source=document.getElementById('exercise-select'), mode=document.getElementById('entry-mode');
let cases=[],lastResult=null,loadedInputs={};
const dataSource=document.getElementById('data-source');
const placeholders={n:'Enter sample / subgroup size, e.g. 9',N:'Enter total lot size, e.g. 2000',mean:'Enter the grand mean, e.g. 26.7',rbar:'Enter the average range, e.g. 5.3',se:'Enter standard error, e.g. 0.5',p:'Enter a proportion from 0 to 1, e.g. 0.02',p0:'Enter the null proportion, e.g. 0.02',c:'Enter maximum accepted defects, e.g. 1',successes:'Enter the number of observed events, e.g. 45',alpha:'Enter significance level, e.g. 0.05',lcl:'Enter the lower control limit, e.g. 3',means:'Enter subgroup means, e.g. 26.1, 26.8, 27.2',ranges:'Enter subgroup ranges, e.g. 4, 5, 6',counts:'Enter defect counts, e.g. 2, 3, 1',proportions:'Enter subgroup proportions, e.g. 0.02, 0.03, 0.01'};
function clearResult(){lastResult=null;document.getElementById('result-content').hidden=true;document.getElementById('empty-result').hidden=false;}
const modes={xbar:[['summary','Grand mean and average range'],['se','Grand mean and known standard error'],['subgroups','Subgroup means and ranges'],['raw','Individual subgroup measurements']],range:[['summary','Average range'],['subgroups','Subgroup means and ranges'],['raw','Individual subgroup measurements']],p:[['summary','Specified proportion'],['counts','Counts by subgroup'],['proportions','Proportions by subgroup']]};
const labels={n:'Subgroup size (n)',N:'Lot size (N)',mean:'Grand mean',rbar:'Average range (R̄)',se:'Known standard error',p:'Proportion (p)',p0:'Null proportion (p₀)',c:'Acceptance number (c)',successes:'Observed events',alpha:'Significance level (α)',lcl:'Lower control limit',means:'Subgroup means',ranges:'Subgroup ranges',observations:'Subgroup measurements',counts:'Counts by subgroup',proportions:'Proportions by subgroup',risk:'Risk to calculate',model:'Probability model'};
function inferredMode(d){if(d.observations)return 'raw';if(d.means)return 'subgroups';if(d.se!==undefined)return 'se';if(Array.isArray(d.counts))return 'counts';if(d.proportions)return 'proportions';return 'summary';}
function fieldKeys(){const k=kind.value,m=mode.value;if(k==='xbar')return m==='raw'?['n','observations']:m==='subgroups'?['n','means','ranges']:m==='se'?['n','mean','se']:['n','mean','rbar'];if(k==='range')return m==='raw'?['n','observations']:m==='subgroups'?['n','means','ranges']:['n','rbar'];if(k==='p')return m==='counts'?['n','p','counts']:m==='proportions'?['n','p','proportions']:['n','p'];if(k==='acceptance')return ['N','n','c','p','risk','model'];if(k==='pareto')return ['counts'];if(k==='proportion_test')return ['n','successes','p0','alpha'];return ['rbar','lcl'];}
function fieldValue(key,d){if(d[key]===undefined)return '';if(key==='observations')return d[key].map(r=>r.join(', ')).join('\n');if(Array.isArray(d[key]))return d[key].join(', ');if(typeof d[key]==='object')return Object.entries(d[key]).map(([label,count])=>`${label}: ${count}`).join('\n');return d[key];}
function renderFields(d={}){const root=document.getElementById('input-fields');root.replaceChildren();for(const key of fieldKeys()){const wrap=document.createElement('div');const label=document.createElement('label');label.htmlFor='value-'+key;label.textContent=labels[key];let input;const list=['means','ranges','observations','counts','proportions'].includes(key);if(list){wrap.className='field-wide';input=document.createElement('textarea');input.value=fieldValue(key,d);input.placeholder=kind.value==='pareto'?'Category A: 25\nCategory B: 10':key==='observations'?'101, 99, 102, 98, 100\n100, 103, 99, 101, 102':'Enter numbers separated by commas';}else if(key==='risk'||key==='model'){input=document.createElement('select');const options=key==='risk'?[['producer','Producer’s risk'],['consumer','Consumer’s risk']]:[['binomial','Binomial'],['poisson','Poisson approximation']];for(const [v,t] of options)input.add(new Option(t,v));input.value=d[key]||options[0][0];}else{input=document.createElement('input');input.type='number';input.step=['n','N','c','successes'].includes(key)?'1':'any';input.value=fieldValue(key,d);if(['n','N'].includes(key))input.min='1';if(['c','rbar','se','lcl','successes'].includes(key))input.min='0';if(['p','p0','alpha'].includes(key)){input.min='0';input.max='1';}}
if(placeholders[key]&&!(kind.value==='pareto'&&key==='counts'))input.placeholder=placeholders[key];input.id='value-'+key;input.name=key;input.required=!(key==='p'&&kind.value==='p'&&mode.value!=='summary');wrap.append(label,input);let help='';if(['p','p0','alpha'].includes(key))help='Use a fraction: 0.02 means 2%.';if(key==='p'&&kind.value==='p'&&mode.value!=='summary')help='Optional target. Leave blank to estimate it from the observed data.';if(key==='observations')help='One subgroup per line, with n comma-separated measurements.';if(kind.value==='pareto'&&key==='counts')help='One category per line: category name: count.';if(help){const hint=document.createElement('p');hint.className='field-hint';hint.textContent=help;wrap.append(hint);}root.append(wrap);}}
function updateModes(d){const choices=modes[kind.value]||[],bookMode=dataSource.value==='book';document.getElementById('mode-container').hidden=bookMode||!choices.length;mode.disabled=bookMode;mode.replaceChildren();choices.forEach(([v,t])=>mode.add(new Option(t,v)));mode.value=inferredMode(d);if(!mode.value&&choices.length)mode.selectedIndex=0;}
function loadExercise(){
 clearResult();
 const c=dataSource.value==='book'?cases.find(c=>c.id===source.value):null;
 loadedInputs=c?structuredClone(c.inputs):{};
 updateModes(loadedInputs);renderFields(c?{risk:loadedInputs.risk,model:loadedInputs.model}:{});
 document.getElementById('input-fields').hidden=dataSource.value==='book'&&!c;
 source.disabled=dataSource.value==='own';
 document.getElementById('source-hint').textContent=dataSource.value==='own'?'Enter your own values. Book comparison is disabled.':c?`Enter your numerical values to compare with ${c.id}, textbook page ${c.page}.`:'Select a question, then enter its numerical values.';
}
function populateSources(){source.replaceChildren(new Option('Select a book question',''));cases.filter(c=>c.kind===kind.value).forEach(c=>source.add(new Option(`${c.id} — ${c.title}`,c.id)));loadExercise();}
function numbers(text){const tokens=text.trim().split(/[\s,;]+/).filter(Boolean);if(!tokens.length)throw Error('Enter at least one numerical value.');return tokens.map(t=>{const n=Number(t);if(!Number.isFinite(n))throw Error(`Invalid numerical value: ${t}`);return n;});}
function collect(){const data={};for(const key of fieldKeys()){const text=document.getElementById('value-'+key).value.trim();if(!text&&key==='p')continue;if(key==='observations')data[key]=text.split(/\n/).filter(l=>l.trim()).map(numbers);else if(key==='counts'&&kind.value==='pareto'){data[key]={};for(const line of text.split(/\n/).filter(l=>l.trim())){const at=line.lastIndexOf(':');if(at<1)throw Error('Use category name: count for each Pareto category.');const label=line.slice(0,at).trim();if(label in data[key])throw Error('Category names must be unique.');const value=line.slice(at+1).trim();if(!value)throw Error('Each category needs a count.');data[key][label]=Number(value);}}else if(['means','ranges','counts','proportions'].includes(key))data[key]=numbers(text);else if(['risk','model'].includes(key))data[key]=text;else{if(!text)throw Error(`Enter ${labels[key]}.`);data[key]=Number(text);}}
// Preserve descriptive metadata, never preserve input values hidden by a new entry mode.
if(dataSource.value==='book'&&source.value){for(const key of ['unit','attribute'])if(loadedInputs[key]!==undefined)data[key]=loadedInputs[key];if(loadedInputs.labels&&((data.means&&data.means.length===loadedInputs.labels.length)||(data.observations&&data.observations.length===loadedInputs.labels.length)))data.labels=loadedInputs.labels;}
return data;}
dataSource.addEventListener('change',loadExercise);kind.addEventListener('change',()=>populateSources(false));source.addEventListener('change',loadExercise);mode.addEventListener('change',()=>{clearResult();renderFields({});});document.getElementById('reset-button').addEventListener('click',loadExercise);
form.addEventListener('submit',async event=>{event.preventDefault();const error=document.getElementById('form-error'),busy=document.getElementById('loading-message'),button=document.getElementById('calculate-button');error.hidden=true;try{if(dataSource.value==='book'&&!source.value)throw Error('Select a book question for comparison.');const inputs=collect();clearResult();button.disabled=true;busy.hidden=false;const response=await fetch('/api/calculate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:kind.value,data_source:dataSource.value,exercise_id:dataSource.value==='book'?source.value:'',inputs,trials:Number(document.getElementById('trials').value)})});const result=await response.json();if(!response.ok)throw Error(result.error||'The calculation could not be completed.');lastResult=result;document.getElementById('empty-result').hidden=true;document.getElementById('result-content').hidden=false;const message=document.getElementById('data-message');message.textContent=result.message;message.className='data-message'+(result.category==='book'?' book-data':'');const frame=document.getElementById('result-frame');frame.srcdoc=result.report_html.replace('</style>',' .topbar,.report-heading,.overview,footer,.subtle-link{display:none!important}main{padding:16px!important}.exercise{padding:20px!important;margin:0!important}.workspace{display:block!important}.panel-heading{align-items:flex-start}.panel-heading p{max-width:220px}</style>');}catch(e){error.textContent=e.message;error.hidden=false;}finally{button.disabled=false;busy.hidden=true;}});
document.getElementById('download-result').addEventListener('click',()=>{if(!lastResult)return;const blob=new Blob([JSON.stringify({message:lastResult.message,category:lastResult.category,record:lastResult.record},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='qc-calculation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
fetch('chapter10_inputs.json').then(r=>{if(!r.ok)throw Error('Unable to load stored exercises.');return r.json();}).then(data=>{cases=data.cases;populateSources(true);}).catch(e=>{const error=document.getElementById('form-error');error.textContent=e.message;error.hidden=false;populateSources(false);});
